version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
        - "3307:3306"
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: docker
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: accounts
    container_name: lifeblood-accounts